name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default branch is different (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push to gh-pages branch
      pages: write    # To deploy to Pages
      id-token: write # To enable OIDC token for passwordless deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          CI: true # Ensures NODE_ENV=production for correct basePath in next.config.ts

      - name: Add .nojekyll to out folder
        run: touch out/.nojekyll

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy: ${{ github.event.head_commit.message }} [skip ci]"
